var o,p,n=nil;
o=[Event.prNew,Array.prNew(16),Event.prNew,Array.prNew(4),Event.prNew,Array.prNew(4)];
p=[0,[array:o[1],size:5,proto:nil,parent:nil,know:true],1,['squelch',1.937592668375,'vol',1.0,'presets',o[2],n,n,'gain',0.16944129493835,n,n,n,n,'res',0.21649545260697],2,[array:o[3],size:1,proto:nil,parent:nil,know:true],3,[n,n,'subdued',o[4]],4,[array:o[5],size:1,proto:nil,parent:nil,know:true],5,['squelch',0.1,n,n]
];
prUnarchive(o,p);
